### ISSUE TITLE
Update dygraph-combined.js and dygraphs on CRAN

### ISSUE THREAD

**Issue by bthieurmel** [rstudio/dygraphs#30] opened 2015-01-22 13:03 UTC
Can you think about updating dygraph-combined.js to 1.1.0 ? Can have some cool improvement (I think about fill charts, which can be long actually...)

* dygraphs is now "retina" compatible.
* Dramatically improved performance for filled charts (i.e. fillGraph)
* More sensible date ticks: "Jan 08"→"Jan 2008", "29Jan"→"29 Jan"
* Using a non-existent option now throws (w/ dygraph-combined-dev.js)
* x-axis log scales
* The labelsUTC option forces UTC formatting for all labels.
* The new DataHandler system allows for more flexibility in data loading.
* "this" is set to the dygraph in all callbacks.
* dygraphs has shrunk, because we moved some stuff into "extras" (133kb→122kb) 

And, when the next CRAN update ? (I think to useDataTimezone to...)

**Comment by jjallaire** [comment] 2015-01-22 13:41
I'm planning on submitting an update to CRAN in the next week or so.

In terms of updating dygraph to 1.1.0, I'd like to do this but the first time I tried in many instances the axis labels went from one line to two lines and started getting clipped. Something changed in the way axis labels are spaced/computed and I don't know enough about dygraphs to sort out what happened or how to work around it. If you can help with this then we can include this work in the update to CRAN.

**Comment by bthieurmel** [comment] 2015-01-22 13:49
Ok. I think I can have a look of this axis problem tomorrow. We can perhaps define a custom axis labels function for dygrahs R package. (In the same way we do with useDataTimezone options, and timezone.js)

**Comment by bthieurmel** [comment] 2015-01-27 15:53
Hi. I'm just doiing some test and try to result the axis problem (not so easy...).
You can look at the PR  "Update to dygraph 1.1.0 - work on label and ticker #31"

**Comment by jjallaire** [comment] 2015-01-27 21:30
Updating to dygraphs 1.1 and solving the axis issues still look a bit sticky. If there are regressions in behavior in dygraphs 1.1 for axis label layout I'd much rather those bugs get fixed in dygraphs than our doing our own custom plotters. Could we report the issues there?

I just updated dygraphs on CRAN so the useDataTimezone option is now available more broadly. I don't have time over the next few weeks to work on another update but if we can get the underlying issues in dygraphs resolved then it should be easy to do the update when I have more time.

**Comment by bthieurmel** [comment] 2015-01-28 09:00
I don't think there are regressions in dygraphs 1.1. Some javascript function change. The difficulties are, for me, just to adapt the change for a fixed tz. 
For "classic" dygraphs, I don't see bug / problem. Can you have time to send me some examples of labels problem using dygraph 1.1 via RStudio ?

**Comment by jjallaire** [comment] 2015-01-28 13:55
Here is what I see with dygraphs 1.0.1 when running the examples.R file from the package (https://github.com/rstudio/dygraphs/blob/master/inst/examples/examples.R):

![dygraphs-1 0 1](https://cloud.githubusercontent.com/assets/104391/5938657/2f9110c2-a6cb-11e4-875e-62923c5faf28.png)

Now here's what I see with dygraphs 1.1.0:

![dygraphs-1 1 0](https://cloud.githubusercontent.com/assets/104391/5938664/39824e84-a6cb-11e4-83ea-21f96e0c9197.png)

The issue seems to be that the default changed to show all four digits of the year however the code that handles tick positioning wasn't updated to reflect this.

It would be ideal if a change were made to dygraphs to overcome this. If that's not possible I guess we could maintain our own fork with this change but I'd really rather not do this.

**Comment by bthieurmel** [comment] 2015-01-28 15:20
Yes, it seems we observe this bug only with monthly data. The update of the ticker isn't perfect with some zoom level... Perhaps we can post your example on dygrahs issues ?

**Comment by jjallaire** [comment] 2015-01-28 15:51
Yes, I think that's a good idea.

**Comment by bthieurmel** [comment] 2015-01-28 16:08
I think it's perhaps a rstudio viewer problem. If we show in a new windows, it seems we don't have overlapping. 
In dygraph.js, you add a default font for the viewer mode. If I delete this, I don't have axis overlapping.

**Comment by bthieurmel** [comment] 2015-01-28 16:24
After some tests, it's quite clear for me that dygraph doesn't take into account the css in the placement of ticks....

**Comment by jjallaire** [comment] 2015-01-28 16:43
So the question is whether we can develop some styles for the RStudio
Viewer that get the ticks right most of the time. I'll dig into this
further.

**Comment by bthieurmel** [comment] 2015-01-28 17:18
Yes. For info, if you really love 'Arial, sans-serif', and want to keep this in the viewer, a font-size of 12.5px seems a good choice for the label !

**Comment by jjallaire** [comment] 2015-01-28 17:48
I've got a branch where this work is now:

https://github.com/rstudio/dygraphs/tree/feature/dygraphs-1.1

I had to set the font size to 11.5 to get the axis to draw reasonably under
the RStudio daily build (which uses a more up to date version of Qt).

Unfortunately, even under Chrome (on Linux) the axis labels are really
jammed together. This is a problem in dygraphs which I think they need to
resolve! I guess if we can't get them to do it we can always provide a
custom valueFormatter that restores some of the old behavior.

**Comment by bthieurmel** [comment] 2015-01-28 18:07
Ok. I'll work on this branch for update customDateTickerFixedTZ function next week. Actually, I think that useDataTimezone return no ticker. The ticker creation processus change a lot in dygraph 1.1.0.
And I hope we can find a good solution for the overlapping problem too.

**Comment by jjallaire** [comment] 2015-01-28 19:52
Great, look forward to getting dygraphs 1.1 support integrated!

**Comment by chrisirhc** [comment] 2015-10-09 00:17
It doesn't look like dygraphs is going to change their axis formatter. Perhaps instead, this project should allow, and recommend, using the `axisLabelWidth` and `pixelsPerLabel` options after updating to dygraphs 1.1 ?

**Comment by chrisirhc** [comment] 2015-10-10 02:29
@jjallaire , submitted a PR incorporating those fixes: #88 .

**Closed** 2015-10-19 08:06 UTC

**Comment by jjallaire** [comment] 2015-10-20 13:54
dygraphs 0.5 (which includes the underlying dygraphs 1.1.1 library) is now on CRAN
