### ISSUE TITLE
CRAN submission

### ISSUE THREAD

**Issue by odelaigue** [rstudio/dygraphs#198] opened 2018-02-05 08:17 UTC
Dear Rstudio Team,

Thank you very much for your job on the dygraphs package that is very useful.
We developed a package to learn hydrological modelling that imports your package (and also shiny). Several months ago we asked you to modify the `dyStackedBarGroup()` function (issue #180) and it worked very well (thank you very much for that!). We would like to put our package on the CRAN, but for that, the latest version of dygraphs should be there too. We would really appreciate if you could submit your package to the CRAN relatively quickly. 
Do you have any idea about when that would be possible?

Kind regards.

**Comment by pshevtsov** [comment] 2018-02-05 10:19
Hello @odelaigue,

Thank you for your interest. I'm going to finish some release-stoppers this week, so hopefully the next week we could submit the new version to CRAN.

Duplicate of #164

**Closed by pshevtsov** 2018-02-05 10:19 UTC
