### ISSUE TITLE
Feature request: numeric x axis

### ISSUE THREAD

**Issue by DatenHelden** [rstudio/dygraphs#40] opened 2015-04-01 20:25 UTC
It would be great if you could integrate a feature that one can provide a numeric R object as x axis llike in the example shown here: http://dygraphs.com/gallery/#g/independent-series

**Comment by bbTomas** [comment] 2015-06-01 14:26
Yes, please. It will be awesome. As I process and a lot of time series from audio files (where the time is relative, it always begins in 0) and their Fourier transform (where the x axis is frequency), these interactive plots would be the best tool for exploratoring.
As the original http://dygraphs.com/ makes it possible to have a numeric axis, it will be cool to impement it also into R. Thanks.

**Comment by jeffjet24** [comment] 2015-08-28 16:24
I would really love to see this feature as well. I love the tool for all of my time series applications, and it would be awesome if I could apply it to my other line plots as well.

Thanks!

**Comment by dgromer** [comment] 2015-08-31 19:18
+1. Would be great for working with time series that are not bound to a specific date (e.g. psychophysiological measures such as electrodermal activity)

**Comment by dgromer** [comment] 2015-09-02 09:04
Getting this functionality to work is quite straightforward: If you simplify the `dygraph` function in `dygraph.R` to

```r
dygraph <- function(data, width = NULL, height = NULL) {
  
  # create widget
  htmlwidgets::createWidget(
    name = "dygraphs",
    x = data,
    width = width,
    height = height,
    htmlwidgets::sizingPolicy(viewer.padding = 10, browser.fill = TRUE)
  )
}
```

and the `renderValue` function in the HTMLWidget to

```js
renderValue: function(el, x, instance) {

    // transpose array
    x = HTMLWidgets.transposeArray2D(x);

    instance.dygraph = new Dygraph(el, x);
}
```

you can plot x/y values with `dygraph(list(1:1000, runif(1000))`. Dygraphs (JavaScript library) parses the x values to determine whether the values are date values or just numbers.

However, the question is how to implement this properly into the r package. What do you think @jjallaire? Does it make sense to include this in the `dygraph` function and HTMLWidget or should this be moved to another widget or package?

**Comment by jjallaire** [comment] 2015-09-02 17:12
The problem is that there are other parts of the code that assume we're
dealing with dates and they'd all have to be changed to deal with either.
Not the hardest thing in the world to do but a bit disruptive so not
something we've done yet.

**Comment by dgromer** [comment] 2015-09-07 21:03
I implemented a preliminary solution for this issue at https://github.com/dgromer/dygraphs.

Example:
```r
dygraph(list(x = 1:10, y = runif(10))) %>%
  dyAxis("y", valueRange = c(0, 1.5)) %>%
  dyEvent(2, label = "test") %>%
  dyAnnotation(5, text = "A")
```

**Comment by bbTomas** [comment] 2015-09-09 10:54
Thank you, @dgromer. This helps so much. Although preliminary, it is 100x better for digital signal processing now.

Do you think, would it be hard to implement highlighted closest series border in legend? (E.g., first two pictures at http://dygraphs.com/gallery/#g/highlighted-series). In original Dygraphs, it can be easily done in .css file:
.dygraph-legend > span.highlight { border: 1px solid grey; }

And another future request, logscale for both x- and y-axis.
In original Dygraphs (e.g., after digitsAfterDecimal and maxNumberWidth properties):
this is for y-axis:
logscale: true

and this is for x-axis:
axes : { x : {  logscale : true } }

Thanks again both @jjallaire for original R implementation and @dgromer for this solution.

**Comment by jjallaire** [comment] 2015-10-26 12:32
Fixed via https://github.com/rstudio/dygraphs/pull/91

**Closed by jjallaire** 2015-10-26 12:32 UTC
